#!/usr/bin/env bash
# Render the demo test plans from live terraform outputs.
#
# Sharding design: no load balancer. The plan gets ONE scenario PER TARGET
# (absolute URL to that target's private IP), each scenario carrying an equal
# slice of the total rate. The controller then partitions every scenario's
# rate across ALL connected agents — so each agent spreads its connections
# over every target, and the fleet-wide rate is exact by construction.
#
# Usage:  ./render-plans.sh            # 2,000,000 rps ladder
#         TOTAL_RPS=500000 ./render-plans.sh
#         CAL_MAX=500000 ./render-plans.sh   # calibration staircase top rate
set -euo pipefail

cd "$(dirname "$0")/.."
TOTAL_RPS="${TOTAL_RPS:-2000000}"
CAL_MAX="${CAL_MAX:-300000}"

mapfile -t IPS < <(terraform -chdir=terraform output -json target_private_ips | jq -r '.[]')
N="${#IPS[@]}"
[ "$N" -gt 0 ] || { echo "no target_private_ips in terraform output — did you apply?" >&2; exit 1; }

SHARE=$(( TOTAL_RPS / N ))
PRE=$(( SHARE / 100 < 200 ? 200 : SHARE / 100 ))   # ~10ms of latency headroom
MAX=$(( SHARE / 20 ))                              # ~50ms of latency headroom
mkdir -p plans

# ---- demo-2m.yaml: the ramp ladder ------------------------------------------
{
cat <<EOF
# GENERATED by scripts/render-plans.sh — do not edit; re-render instead.
# ${TOTAL_RPS} req/s total, sharded over ${N} targets (${SHARE}/s each),
# each scenario partitioned across every connected agent by the controller.
name: demo-2m-rps
description: ${TOTAL_RPS} req/s fleet-wide, ladder 12.5% -> 25% -> 50% -> 100%

scenarios:
EOF
i=0
for ip in "${IPS[@]}"; do
cat <<EOF
  target_$(printf '%02d' "$i"):
    executor: ramping-arrival-rate
    start_rate: 100
    time_unit: 1s
    pre_allocated_vus: ${PRE}
    max_vus: ${MAX}
    stages:
      # 14 minutes total — fits a 15-minute demo slot with a minute to talk.
      - { duration: 1m,  target: $(( SHARE / 8 )) }  # ramp to 12.5%
      - { duration: 90s, target: $(( SHARE / 8 )) }  # hold
      - { duration: 1m,  target: $(( SHARE / 4 )) }  # ramp to 25%
      - { duration: 90s, target: $(( SHARE / 4 )) }  # hold
      - { duration: 1m,  target: $(( SHARE / 2 )) }  # ramp to 50%
      - { duration: 90s, target: $(( SHARE / 2 )) }  # hold
      - { duration: 90s, target: ${SHARE} }          # ramp to 100%
      - { duration: 5m,  target: ${SHARE} }          # the money shot
    flow:
      - request:
          name: json
          method: GET
          url: http://${ip}:8080/json
          checks:
            - { type: status, equals: 200 }
EOF
i=$(( i + 1 ))
done
cat <<'EOF'

thresholds:
  http_req_duration: [ "p(99)<100" ]
  http_req_failed: [ "rate<0.005" ]
EOF
} > plans/demo-2m.yaml

# ---- calibrate.yaml: single-agent ceiling finder -----------------------------
# Run with agent_count=1. Watch dropped_iterations in the UI: the rate at
# which drops begin is that instance type's ceiling. Size the fleet as
# ceil(TOTAL_RPS / (ceiling * 0.7)).
#
# Sharded across ALL targets (like the demo plan) so the staircase measures
# the AGENT's ceiling, not a single target's. Six even steps up to CAL_MAX.
CAL_SHARE=$(( CAL_MAX / N ))
CAL_PRE=$(( CAL_SHARE / 100 < 100 ? 100 : CAL_SHARE / 100 ))
CAL_VMAX=$(( CAL_SHARE / 10 ))
{
cat <<EOF
# GENERATED by scripts/render-plans.sh — do not edit; re-render instead.
# No thresholds on purpose: this run is SUPPOSED to hit the wall.
# ${CAL_MAX}/s top rate, sharded over ${N} targets (${CAL_SHARE}/s each).
name: calibrate-agent-ceiling
description: staircase one agent to ${CAL_MAX}/s and note where dropped_iterations begins

scenarios:
EOF
i=0
for ip in "${IPS[@]}"; do
cat <<EOF
  target_$(printf '%02d' "$i"):
    executor: ramping-arrival-rate
    start_rate: $(( CAL_SHARE / 60 + 1 ))
    time_unit: 1s
    pre_allocated_vus: ${CAL_PRE}
    max_vus: ${CAL_VMAX}
    stages:
EOF
for step in 1 2 3 4 5 6; do
cat <<EOF
      - { duration: 1m,  target: $(( CAL_SHARE * step / 6 )) }
      - { duration: 30s, target: $(( CAL_SHARE * step / 6 )) }
EOF
done
cat <<EOF
    flow:
      - request:
          name: json
          method: GET
          url: http://${ip}:8080/json
          checks:
            - { type: status, equals: 200 }
EOF
i=$(( i + 1 ))
done
} > plans/calibrate.yaml

echo "rendered plans/demo-2m.yaml   (${N} scenarios x ${SHARE}/s = ${TOTAL_RPS}/s)"
echo "rendered plans/calibrate.yaml (${N} scenarios, staircase to ${CAL_MAX}/s total)"
