# Generated by packaging/render-packages.sh — do not edit by hand.
# Tap: brew tap levantar-ai/loadr https://github.com/levantar-ai/loadr
class Loadr < Formula
  desc "Modern load-testing tool: declarative YAML, embedded JS, many protocols"
  homepage "https://loadr.io"
  version "1.23.0"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.23.0/loadr-aarch64-apple-darwin.tar.gz"
      sha256 "368f78ae413ac3182171d60ba91613f1b136ea86fd825d5949d2867d3b350a80"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.23.0/loadr-x86_64-apple-darwin.tar.gz"
      sha256 "267958bf5397b8fbe7d2ace675205697de770be7599338fa05d6cc7789a1ffce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.23.0/loadr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6767203fbcb33923d95e37b4a89c111b7a64d812d9ae5ecab3b7965bd0284e3f"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.23.0/loadr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a39e23c30f9ccc52e8d7e9500c4482a6223ee2eaf6743574b5b69cf67091b889"
    end
  end

  def install
    bin.install "loadr"
  end

  test do
    assert_match "loadr", shell_output("#{bin}/loadr --version")
  end
end
