# Generated by packaging/render-packages.sh — do not edit by hand.
# Tap: brew tap levantar-ai/loadr https://github.com/levantar-ai/loadr
class Loadr < Formula
  desc "Modern load-testing tool: declarative YAML, embedded JS, many protocols"
  homepage "https://loadr.io"
  version "1.22.3"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.22.3/loadr-aarch64-apple-darwin.tar.gz"
      sha256 "70530df1f2270cb23be46a209603e2dad3af4651c7877264cebf7c53e7102b88"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.22.3/loadr-x86_64-apple-darwin.tar.gz"
      sha256 "c8e2c4b8056d8437748590f723bf9e3700a2c190aa7f927200e050c9dde83d14"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.22.3/loadr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "fa56b457627b5a27e130c688d15b157065a85f646f5cecb4c9c577e021c753cd"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.22.3/loadr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f04f74f9c05ead6b0eb13da51cc386785c35d1d8d64aa9198b024498ab29bb83"
    end
  end

  def install
    bin.install "loadr"
  end

  test do
    assert_match "loadr", shell_output("#{bin}/loadr --version")
  end
end
