# Generated by packaging/render-packages.sh — do not edit by hand.
# Tap: brew tap levantar-ai/loadr https://github.com/levantar-ai/loadr
class Loadr < Formula
  desc "Modern load-testing tool: declarative YAML, embedded JS, many protocols"
  homepage "https://loadr.io"
  version "1.29.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.29.0/loadr-aarch64-apple-darwin.tar.gz"
      sha256 "7319ea7c091a2c9ab3351f1d9be65a840bb9b48ca8d8fbf13971dbc2d872c4db"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.29.0/loadr-x86_64-apple-darwin.tar.gz"
      sha256 "db6962b1c16ee4a0943406be8337d385c8265fbc2ff1806e248447fc5916f185"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.29.0/loadr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9fe4461db58335fad6671ef047caafd7004752eaad7b9f3bbf8b522d63614c93"
    end
    on_intel do
      url "https://github.com/levantar-ai/loadr/releases/download/v1.29.0/loadr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5d373a9ca6e13069e4e7bd910467547f6bcb034f7923c075edbc7bee2a3c67c4"
    end
  end

  def install
    bin.install "loadr"
  end

  test do
    assert_match "loadr", shell_output("#{bin}/loadr --version")
  end
end
