#!/usr/bin/env bash
# Generate the Homebrew formula (Formula/loadr.rb) and Scoop manifest
# (bucket/loadr.json) for a given CLI release, pulling SHA-256s straight from the
# release's SHA256SUMS. One source of truth; run locally or by publish-packages.yml.
#   packaging/render-packages.sh v1.21.5   (or just 1.21.5)
set -euo pipefail
VER="${1:?usage: render-packages.sh <version, e.g. v1.21.5>}"; VER="${VER#v}"
REPO="levantar-ai/loadr"
BASE="https://github.com/$REPO/releases/download/v$VER"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

sums="$(curl -fsSL "$BASE/SHA256SUMS")"
sha() { awk -v f="$1" '$2==f {print $1}' <<<"$sums"; }
MAC_ARM=$(sha loadr-aarch64-apple-darwin.tar.gz)
MAC_X64=$(sha loadr-x86_64-apple-darwin.tar.gz)
LNX_ARM=$(sha loadr-aarch64-unknown-linux-gnu.tar.gz)
LNX_X64=$(sha loadr-x86_64-unknown-linux-gnu.tar.gz)
WIN_X64=$(sha loadr-x86_64-pc-windows-msvc.zip)
for v in MAC_ARM MAC_X64 LNX_ARM LNX_X64 WIN_X64; do
  [ -n "${!v}" ] || { echo "missing SHA-256 for $v in v$VER SHA256SUMS" >&2; exit 1; }
done

mkdir -p "$ROOT/Formula" "$ROOT/bucket"

cat > "$ROOT/Formula/loadr.rb" <<RUBY
# Generated by packaging/render-packages.sh — do not edit by hand.
# Tap: brew tap levantar-ai/loadr https://github.com/levantar-ai/loadr
class Loadr < Formula
  desc "Modern load-testing tool: declarative YAML, embedded JS, many protocols"
  homepage "https://loadr.io"
  version "$VER"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "$BASE/loadr-aarch64-apple-darwin.tar.gz"
      sha256 "$MAC_ARM"
    end
    on_intel do
      url "$BASE/loadr-x86_64-apple-darwin.tar.gz"
      sha256 "$MAC_X64"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/loadr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$LNX_ARM"
    end
    on_intel do
      url "$BASE/loadr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$LNX_X64"
    end
  end

  def install
    bin.install "loadr"
  end

  test do
    assert_match "loadr", shell_output("#{bin}/loadr --version")
  end
end
RUBY

cat > "$ROOT/bucket/loadr.json" <<JSON
{
  "version": "$VER",
  "description": "Modern load-testing tool: declarative YAML, embedded JS, many protocols",
  "homepage": "https://loadr.io",
  "license": "Elastic-2.0",
  "architecture": {
    "64bit": {
      "url": "$BASE/loadr-x86_64-pc-windows-msvc.zip",
      "hash": "$WIN_X64",
      "extract_dir": "loadr-x86_64-pc-windows-msvc"
    }
  },
  "bin": "loadr.exe",
  "checkver": "github",
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/$REPO/releases/download/v\$version/loadr-x86_64-pc-windows-msvc.zip"
      }
    },
    "hash": { "url": "\$url.sha256" }
  }
}
JSON

echo "wrote Formula/loadr.rb and bucket/loadr.json for v$VER"
